---
title: "ISL_CH8_Trees"
output: html_document
---

[Class Resources](https://courses.edx.org/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/ch8.html)
[Other Resources](https://blog.princehonest.com/stat-learning/)

# DECISION TREES

## DATA: Carseats
## PACKAGE: `tree`

```{r}
rm(Sales)
rm(High)
rm(Carseats)
rm(high_binary)
require(ISLR)
require(tree)
attach(Carseats)
hist(Sales)
# High=ifelse(Sales<=8,"No","Yes")
# Carseats=data.frame(Carseats,High)
# tree.carseats=tree(High~.-Sales,Carseats)
# summary(tree.carseats)
# plot(tree.carseats)

# High=ifelse(Sales<=8,"No", "Yes")
# hist(High)
# Carseats=data.frame(Carseats,High)
# Carseats=data.frame(Carseats)
# Carseats = na.omit(Carseats)
# tree.carseats =tree(High~.-Sales , Carseats )
# test = na.omit(tree.carseats)
# summary(test)
```

```{r}
summary(Carseats)
lm.fit=lm(Sales~Advertising+Price,data=Carseats)
```

```{r}
# tree.carseats=tree(High~.-Sales,data=Carseats)
# summary(tree.carseats)
# plot(tree.carseats)
```



-----
```{r}
high_binary = ifelse(Sales <= 8,0,1)
c_df = data.frame(Carseats, high_binary)
high_binary
c_df
tree.carseats=tree(high_binary~.-Sales,data=c_df)
summary(tree.carseats)
plot(tree.carseats)
```   
```{r}
high_binary = ifelse(Sales <= 8,0,1)
c_df = data.frame(Carseats, high_binary)
high_binary
c_df
tree.carseats=tree(high_binary~.-Sales,data=c_df)
summary(tree.carseats)
plot(tree.carseats)
text(tree.carseats, pretty=0)
```
## DETAILED SUMMARY OF TREE and ALL terminal nodes

```{r}
# tree.carseats
```

## Now, we want to TRAIN our Tree and TEST our tree!
1. Create a training and test (use a set seed!) set by...
2. Splitting the 400 observations into (250,150) and...
3. Growing the tree on the training set before ...
4. Evaluating the performance on the test set


```{r}
# set.seed(315)
# # take a 250 size sample of 1:number of rows in Carseats
# # this simply generates a list of ids
# train=sample(1:nrow(c_df),250)
# tree.carseats=tree(high_binary~.-Sales,c_df,subset=train)
# plot(tree.carseats);text(tree.carseats,pretty=0)
```

## TRYING AGAIN

[stack overflow](https://stackoverflow.com/questions/31843212/r-predict-func-type-class-error) 
to help with the "class" only used for classification error
Had to add "as.factor" to our binary 
```{r}
set.seed(315)
# take a 250 size sample of 1:number of rows in Carseats
# this simply generates a list of ids

hb_f = as.factor(high_binary)
train=sample(1:nrow(c_df),250)
tree.carseats=tree(hb_f~.-Sales,c_df,subset=train)
plot(tree.carseats);text(tree.carseats,pretty=0)
tree.pred=predict(tree.carseats, c_df[-train], type="class")
with(c_df[-train,],table(tree.pred,hb_f))
72+33/150
```

## Misclassification table
The diagonals in the table above are the incorrect classifications

----------------------

# RANDOM FORESTS AND BOOSTING

## Random Forests

## Boosting
